export const INCREMENT = 'INCREMENT'
export const DECREMENT = 'DECREMENT'

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR'

export const CREATE_NEW_USER_REQUEST = 'CREATE_NEW_USER_REQUEST'
export const CREATE_NEW_USER_SUCCESS = 'CREATE_NEW_USER_SUCCESS'
export const CREATE_NEW_USER_ERROR = 'CREATE_NEW_USER_ERROR'